---

name: Slack Notify

on:
  repository_dispatch:
    types: [workflow_failed]
  workflow_dispatch:
    inputs:
      repo:     { required: true }
      job:      { required: true }
      run_id:   { required: true }
      workflow: { required: true }

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          REPO: ${{ github.event.inputs.repo || github.repository }}
          JOB: ${{ github.event.inputs.job || github.job }}
          RUN_ID: ${{ github.event.inputs.run_id || github.run_id }}
          WORKFLOW: ${{ github.event.inputs.workflow || github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: failure
          SLACK_TITLE: "${{ env.WORKFLOW }} / ${{ env.JOB }} Failed"
          MSG_MINIMAL: true
          SLACK_MESSAGE: "Run: https://github.com/${{ env.REPO }}/actions/runs/${{ env.RUN_ID }}"

