---

name: Slack Notify

on:
  repository_dispatch:
    types: [workflow_failed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: failure
          SLACK_TITLE: "${{ github.workflow }} / ${{ github.job }} Failed"
          MSG_MINIMAL: true
          SLACK_MESSAGE: "Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

