---

name: Slack Notify

on:
  repository_dispatch:
    types: [workflow_failed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          REPO: ${{ github.event.client_payload.repo || github.repository }}
          JOB: ${{ github.event.client_payload.job || github.job }}
          RUN_ID: ${{ github.event.client_payload.run_id || github.run_id }}
          WORKFLOW: ${{ github.event.client_payload.workflow || github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: failure
          SLACK_TITLE: "${{ env.WORKFLOW }} / ${{ env.JOB }} Failed"
          MSG_MINIMAL: true
          SLACK_MESSAGE: "Run: https://github.com/${{ github.REPO }}/actions/runs/${{ github.RUN_ID }}"

